version: '3.8'

services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@buildbar.eu
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-volume:/pgadmin
      - ./servers.json:/pgadmin4/servers.json

volumes:
  pgadmin-volume:
  postgres-volume:
